// <auto-generated />
namespace Data.Arcoline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202002171742555_init-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
